In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
a.itemsize #returns the size of the array in bytes

4

In [3]:
a=np.array([1,2,3],dtype=np.float64) #it increases the size of the  elements in an array
a.itemsize

8

In [4]:
a

array([1., 2., 3.])

In [5]:
a.shape

(3,)

In [8]:
a=np.array([[1,2],[3,5],[5,6]])
a.shape #returns the shape of an array in terms of rows and columns

(3, 2)

In [10]:
a=np.array([1,2,3],dtype=complex) #turns the elements value into complex values

In [11]:
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
np.arange(1,5) #returns the numbers from 1 to 4


array([1, 2, 3, 4])

In [16]:
np.linspace(1,5,10) #creates an evenly splaced sequence

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [17]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [18]:
a=np.array([[1,2],[3,5],[5,6]])
a.shape

(3, 2)

In [25]:
a=np.array([[1,2],[3,5],[5,6]])
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [5],
       [5],
       [6]])

In [26]:
a.ravel() #turns the multi-dimensional array into an contiguous flattened array

array([1, 2, 3, 5, 5, 6])

In [27]:
a.min() #returns the minimun value 

1

In [28]:
a.max() #returns the maximum value

6

In [29]:
a.sum() #returns the sum of the array

22

In [30]:
a.sum(axis=0) #returns the sum values in column wise

array([ 9, 13])

In [31]:
np.sqrt(a) #returns the squareroot values

array([[1.        , 1.41421356],
       [1.73205081, 2.23606798],
       [2.23606798, 2.44948974]])

In [32]:
a

array([[1, 2],
       [3, 5],
       [5, 6]])

In [33]:
np.std(a) #returns the standard deviation

1.7950549357115015

In [35]:
a= np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])

In [36]:
a+b

array([[ 6,  8],
       [10, 12]])

In [37]:
a-b

array([[-4, -4],
       [-4, -4]])

In [39]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [40]:
#idexing and slicing
n = [6,7,8]
n[0:2] 

[6, 7]

In [41]:
n[-1] #negative indexing

8

In [42]:
a= np.array([6,7,8])

In [43]:
a[0:2]

array([6, 7])

In [44]:
a=np.array([[1,2,4],[3,5,7],[5,6,8]])

In [45]:
a

array([[1, 2, 4],
       [3, 5, 7],
       [5, 6, 8]])

In [46]:
a[1,2] #returns the value from 2nd row 3rd column

7

In [47]:
a[0:2,2]

array([4, 7])

In [48]:
a[-1]

array([5, 6, 8])

In [50]:
a[:,1:3]

array([[2, 4],
       [5, 7],
       [6, 8]])

In [51]:
for row in a:
    print(row) #iterating through the row

[1 2 4]
[3 5 7]
[5 6 8]


In [52]:
for cell in a.flat:
    print(cell)

1
2
4
3
5
7
5
6
8


In [59]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

In [60]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [61]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [62]:
np.vstack((a,b)) #stack the array vertically

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [66]:
np.hstack((a,b)) #stacks the array horizontally

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [67]:
a= np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [68]:
np.hsplit(a,3) #horizontal split

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [69]:
result = np.hsplit(a,3)
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [70]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [71]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [72]:
a = np.arange(12).reshape(3,4)

In [73]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
b =a>4 #boolean operator
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [75]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [76]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [77]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [79]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [81]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [83]:
for x in np.nditer(a,order='c'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [84]:
for x in np.nditer(a,order='f'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [86]:
for x in np.nditer(a,order='f',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [87]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x

In [88]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [90]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [91]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
